---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-socks
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.socks_proxy.type }}
  ports:
    - protocol: {{ .Values.service.socks_proxy.protocol | default "tcp" }}
      port: {{ .Values.service.socks_proxy.port }}
      targetPort: {{ .Values.service.socks_proxy.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-http
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.http_proxy.type }}
  ports:
    - protocol: {{ .Values.service.http_proxy.protocol | default "tcp" }}
      port: {{ .Values.service.http_proxy.port }}
      targetPort: {{ .Values.service.http_proxy.targetPort }}
