name: Release Helm Chart to ArtifactHub

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3.3.0

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.CR_TOKEN }}
        CR_TOKEN: ${{ secrets.CR_TOKEN }}
